-- All browser roles are denied. Application service code performs authorization.
create extension if not exists pgcrypto;
create type payroll_status as enum ('draft','reviewed','finalized','paid','void');
create type overtime_status as enum ('pending','approved','rejected');
create table employees(id uuid primary key default gen_random_uuid(),employee_code text unique not null,display_name text not null,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(display_name));
create table attendance_logs(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees(id) on delete restrict,clock_in_at timestamptz not null,clock_out_at timestamptz,source text not null default 'kiosk',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by_admin text,last_edited_by_admin text,check(clock_out_at is null or clock_out_at>=clock_in_at));
create unique index one_open_attendance_per_employee on attendance_logs(employee_id) where clock_out_at is null;
create table attendance_log_revisions(id uuid primary key default gen_random_uuid(),attendance_log_id uuid not null references attendance_logs(id) on delete restrict,old_values jsonb not null,new_values jsonb not null,reason text not null,admin_identifier text not null,created_at timestamptz not null default now());
create table my_pay_credentials(employee_id uuid primary key references employees(id) on delete restrict,credential_hash text not null,failed_attempt_count int not null default 0,locked_until timestamptz,credential_created_at timestamptz not null default now(),credential_updated_at timestamptz not null default now());
create table my_pay_reset_requests(id uuid primary key default gen_random_uuid(),employee_id uuid unique not null references employees(id) on delete restrict,status text not null default 'pending',requested_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by text,review_notes text);
create table employee_qr_codes(id uuid primary key default gen_random_uuid(),employee_id uuid unique not null references employees(id) on delete restrict,storage_path text not null unique,mime_type text not null,file_size bigint not null check(file_size<=5242880),uploaded_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table daily_rate_history(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees(id) on delete restrict,daily_rate numeric(12,2) not null check(daily_rate>=0),currency text not null default 'PHP',effective_from date not null,effective_to date,notes text,created_by text not null,created_at timestamptz not null default now(),check(effective_to is null or effective_to>=effective_from));
create table overtime_records(id uuid primary key default gen_random_uuid(),employee_id uuid not null references employees(id) on delete restrict,attendance_log_id uuid references attendance_logs(id) on delete restrict,work_date date not null,overtime_minutes integer not null check(overtime_minutes>=0),multiplier numeric(5,2) not null,status overtime_status not null default 'pending',notes text,approved_by text,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table payroll_periods(id uuid primary key default gen_random_uuid(),period_start date not null unique,period_end date not null,status payroll_status not null default 'draft',created_at timestamptz not null default now(),finalized_at timestamptz,paid_at timestamptz,check(period_end=period_start+6));
create table payroll_payouts(id uuid primary key default gen_random_uuid(),payroll_period_id uuid not null references payroll_periods(id) on delete restrict,employee_id uuid not null references employees(id) on delete restrict,computed_regular_pay numeric(12,2) not null default 0,computed_overtime_pay numeric(12,2) not null default 0,computed_bonus_total numeric(12,2) not null default 0,computed_adjustment_total numeric(12,2) not null default 0,computed_gross_pay numeric(12,2) not null default 0,manual_override_amount numeric(12,2),manual_override_reason text,final_payout_amount numeric(12,2) not null,currency text not null default 'PHP',reference_number text,payment_method text,payment_date date,employee_notes text,private_admin_notes text,status payroll_status not null default 'draft',created_by text not null,finalized_by text,paid_by text,created_at timestamptz not null default now(),finalized_at timestamptz,paid_at timestamptz,unique(payroll_period_id,employee_id),check(manual_override_amount is null or manual_override_reason is not null));
create table payroll_line_items(id uuid primary key default gen_random_uuid(),payroll_payout_id uuid not null references payroll_payouts(id) on delete restrict,attendance_log_id uuid references attendance_logs(id) on delete restrict,work_date date,line_type text not null,description text,quantity numeric(12,2),unit_rate numeric(12,2),multiplier numeric(8,4),amount numeric(12,2) not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table application_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
create table admin_audit_logs(id uuid primary key default gen_random_uuid(),actor text not null,action text not null,entity_type text not null,entity_id text not null,previous_data jsonb,new_data jsonb,reason text,created_at timestamptz not null default now());
alter table employees enable row level security; alter table attendance_logs enable row level security; alter table payroll_payouts enable row level security; alter table my_pay_credentials enable row level security;
-- Atomically prevents duplicate clock-in by relying on the partial unique index.
create or replace function clock_employee(p_employee_id uuid) returns text language plpgsql security definer as $$ declare open_log uuid; begin select id into open_log from attendance_logs where employee_id=p_employee_id and clock_out_at is null for update; if open_log is null then insert into attendance_logs(employee_id,clock_in_at) values(p_employee_id,now()); return 'clocked_in'; end if; update attendance_logs set clock_out_at=now(),updated_at=now() where id=open_log; return 'clocked_out'; end $$;
insert into application_settings(key,value) values ('payroll', '{"timezone":"Asia/Manila","currency":"PHP","week_start":"monday","standard_daily_hours":8,"default_overtime_multiplier":1.25,"my_pay_session_minutes":15,"qr_upload_limit_bytes":5242880}');
